# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    target-branch: main
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
