language: python
sudo: false

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: pypy3
          env: TOXENV=pypy3
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
          dist: xenial
          sudo: true
        - python: 3.8
          env: TOXENV=py38
          dist: xenial
          sudo: true

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

notifications:
  email:
    - pyramid-checkins@lists.repoze.org
  irc:
    channels:
      - "chat.freenode.net#pyramid"
