import os
import pytest
import sys
import subprocess

WIN = sys.platform == 'win32'
WORKING = os.path.abspath(os.path.join(os.path.curdir))

base_files = [
    '.coveragerc',
    '.gitignore',
    '/myapp/__init__.py',
    '/myapp/routes.py',
    '/myapp/static/pyramid-16x16.png',
    '/myapp/static/pyramid.png',
    '/myapp/static/theme.css',
    '/myapp/templates/404.template_extension',
    '/myapp/templates/layout.template_extension',
    '/myapp/templates/mytemplate.template_extension',
    '/myapp/tests.py',
    '/myapp/views/__init__.py',
    '/myapp/views/default.py',
    '/myapp/views/notfound.py',
    'CHANGES.txt',
    'MANIFEST.in',
    'README.txt',
    'development.ini',
    'production.ini',
    'pytest.ini',
    'setup.py'
]

sqlalchemy_files = [
    '.coveragerc',
    '.gitignore',
    '/myapp/__init__.py',
    '/myapp/alembic/env.py',
    '/myapp/alembic/script.py.mako',
    '/myapp/alembic/versions/README.txt',
    '/myapp/models/__init__.py',
    '/myapp/models/meta.py',
    '/myapp/models/mymodel.py',
    '/myapp/pshell.py',
    '/myapp/routes.py',
    '/myapp/scripts/__init__.py',
    '/myapp/scripts/initialize_db.py',
    '/myapp/static/pyramid-16x16.png',
    '/myapp/static/pyramid.png',
    '/myapp/static/theme.css',
    '/myapp/templates/404.template_extension',
    '/myapp/templates/layout.template_extension',
    '/myapp/templates/mytemplate.template_extension',
    '/myapp/tests.py',
    '/myapp/views/__init__.py',
    '/myapp/views/default.py',
    '/myapp/views/notfound.py',
    'CHANGES.txt',
    'MANIFEST.in',
    'README.txt',
    'development.ini',
    'production.ini',
    'pytest.ini',
    'setup.py'
]

zodb_files = [
    '.coveragerc',
    '.gitignore',
    '/myapp/__init__.py',
    '/myapp/models/__init__.py',
    '/myapp/pshell.py',
    '/myapp/routes.py',
    '/myapp/static/pyramid-16x16.png',
    '/myapp/static/pyramid.png',
    '/myapp/static/theme.css',
    '/myapp/templates/404.template_extension',
    '/myapp/templates/layout.template_extension',
    '/myapp/templates/mytemplate.template_extension',
    '/myapp/tests.py',
    '/myapp/views/__init__.py',
    '/myapp/views/default.py',
    '/myapp/views/notfound.py',
    'CHANGES.txt',
    'MANIFEST.in',
    'README.txt',
    'development.ini',
    'production.ini',
    'pytest.ini',
    'setup.py'
]


def build_files_list(root_dir):
    """Build a list containing relative paths to the generated files."""
    file_list = []
    for dirpath, subdirs, files in os.walk(root_dir):
        for file_path in files:
            file_list.append(os.path.join(dirpath[len(root_dir):], file_path))

    return file_list


@pytest.mark.parametrize('template', ['jinja2', 'mako', 'chameleon'])
def test_base(cookies, venv, capfd, template):
    result = cookies.bake(extra_context={
        'project_name': 'Test Project',
        'template_language': template,
        'backend': 'none',
        'repo_name': 'myapp',
    })

    assert result.exit_code == 0

    out, err = capfd.readouterr()

    # Get the file list generated by cookiecutter. Differs based on backend.
    files = build_files_list(str(result.project))
    files.sort()

    # Rename files based on template being used
    if template == 'chameleon':
        template = 'pt'

    base_files[7] = base_files[7].split('.')[0] + '.' + template
    base_files[8] = base_files[8].split('.')[0] + '.' + template
    base_files[9] = base_files[9].split('.')[0] + '.' + template

    assert base_files == files

    if WIN:
        assert 'Scripts\\pserve' in out
    else:
        assert 'bin/pserve' in out

    cwd = result.project.strpath

    # this is a hook for executing scaffold tests against a specific
    # version of pyramid (or a local checkout on disk)
    if 'OVERRIDE_PYRAMID' in os.environ:  # pragma: no cover
        venv.install(os.environ['OVERRIDE_PYRAMID'], editable=True)

    venv.install(cwd + '[testing]', editable=True)
    subprocess.check_call([venv.python, '-m', 'pytest', '-q'], cwd=cwd)


@pytest.mark.parametrize('template', ['jinja2', 'mako', 'chameleon'])
def test_zodb(cookies, venv, capfd, template):
    result = cookies.bake(extra_context={
        'project_name': 'Test Project',
        'template_language': template,
        'backend': 'zodb',
        'repo_name': 'myapp',
    })

    assert result.exit_code == 0

    out, err = capfd.readouterr()

    # Get the file list generated by cookiecutter. Differs based on backend.
    files = build_files_list(str(result.project))
    files.sort()

    # Rename files based on template being used
    if template == 'chameleon':
        template = 'pt'

    zodb_files[9] = zodb_files[9].split('.')[0] + '.' + template
    zodb_files[10] = zodb_files[10].split('.')[0] + '.' + template
    zodb_files[11] = zodb_files[11].split('.')[0] + '.' + template

    assert zodb_files == files

    if WIN:
        assert 'Scripts\\pserve' in out
    else:
        assert 'bin/pserve' in out

    cwd = result.project.strpath

    # this is a hook for executing scaffold tests against a specifick
    # version of pyramid (or a local checkout on disk)
    if 'OVERRIDE_PYRAMID' in os.environ:  # pragma: no cover
        venv.install(os.environ['OVERRIDE_PYRAMID'], editable=True)

    venv.install(cwd + '[testing]', editable=True)
    subprocess.check_call([venv.python, '-m', 'pytest', '-q'], cwd=cwd)


@pytest.mark.parametrize('template', ['jinja2', 'mako', 'chameleon'])
def test_sqlalchemy(cookies, venv, capfd, template):
    result = cookies.bake(extra_context={
        'project_name': 'Test Project',
        'template_language': template,
        'backend': 'sqlalchemy',
        'repo_name': 'myapp',
    })

    assert result.exit_code == 0

    out, err = capfd.readouterr()

    # Get the file list generated by cookiecutter. Differs based on backend.
    files = build_files_list(str(result.project))
    files.sort()

    # Rename files based on template being used
    if template == 'chameleon':
        template = 'pt'

    sqlalchemy_files[16] = sqlalchemy_files[16].split('.')[0] + '.' + template
    sqlalchemy_files[17] = sqlalchemy_files[17].split('.')[0] + '.' + template
    sqlalchemy_files[18] = sqlalchemy_files[18].split('.')[0] + '.' + template

    assert sqlalchemy_files == files

    if WIN:
        assert 'Scripts\\pserve' in out
    else:
        assert 'bin/pserve' in out

    cwd = result.project.strpath

    # this is a hook for executing scaffold tests against a specifick
    # version of pyramid (or a local checkout on disk)
    if 'OVERRIDE_PYRAMID' in os.environ:  # pragma: no cover
        venv.install(os.environ['OVERRIDE_PYRAMID'], editable=True)

    venv.install(cwd + '[testing]', editable=True)
    subprocess.check_call([venv.python, '-m', 'pytest', '-q'], cwd=cwd)


def test_it_invalid_module_name(cookies, venv, capfd):
    result = cookies.bake(extra_context={
        'repo_name': '0invalid',
    })
    assert result.exit_code == -1
