import os
import pytest
import sys
import subprocess
import textwrap

WIN = sys.platform == 'win32'
WORKING = os.path.abspath(os.path.join(os.path.curdir))

CONFIG_BASENAMES = [
    'development',
    'production',
    'testing',
]

CONFIG_EXTS = [
    'ini',
    'yaml',
]

BASE_FILES = [
    '.gitignore',
    '/myapp/__init__.py',
    '/myapp/routes.py',
    '/myapp/static/pyramid-16x16.png',
    '/myapp/static/pyramid.png',
    '/myapp/static/theme.css',
    '/myapp/templates/404.template_extension',
    '/myapp/templates/layout.template_extension',
    '/myapp/templates/mytemplate.template_extension',
    '/myapp/views/__init__.py',
    '/myapp/views/default.py',
    '/myapp/views/notfound.py',
    '/tests/__init__.py',
    '/tests/conftest.py',
    '/tests/test_functional.py',
    '/tests/test_views.py',
    'MANIFEST.in',
    'README.md',
    'pyproject.toml',
]

SQLALCHEMY_FILES = [
    '.gitignore',
    '/myapp/__init__.py',
    '/myapp/alembic/env.py',
    '/myapp/alembic/script.py.mako',
    '/myapp/alembic/versions/README.txt',
    '/myapp/models/__init__.py',
    '/myapp/models/meta.py',
    '/myapp/models/mymodel.py',
    '/myapp/pshell.py',
    '/myapp/routes.py',
    '/myapp/scripts/__init__.py',
    '/myapp/scripts/initialize_db.py',
    '/myapp/static/pyramid-16x16.png',
    '/myapp/static/pyramid.png',
    '/myapp/static/theme.css',
    '/myapp/templates/404.template_extension',
    '/myapp/templates/layout.template_extension',
    '/myapp/templates/mytemplate.template_extension',
    '/myapp/views/__init__.py',
    '/myapp/views/default.py',
    '/myapp/views/notfound.py',
    '/tests/__init__.py',
    '/tests/conftest.py',
    '/tests/test_functional.py',
    '/tests/test_views.py',
    'MANIFEST.in',
    'README.md',
    'pyproject.toml',
]

ZODB_FILES = [
    '.gitignore',
    '/myapp/__init__.py',
    '/myapp/models/__init__.py',
    '/myapp/pshell.py',
    '/myapp/routes.py',
    '/myapp/static/pyramid-16x16.png',
    '/myapp/static/pyramid.png',
    '/myapp/static/theme.css',
    '/myapp/templates/404.template_extension',
    '/myapp/templates/layout.template_extension',
    '/myapp/templates/mytemplate.template_extension',
    '/myapp/views/__init__.py',
    '/myapp/views/default.py',
    '/myapp/views/notfound.py',
    '/tests/__init__.py',
    '/tests/conftest.py',
    '/tests/test_functional.py',
    '/tests/test_views.py',
    'MANIFEST.in',
    'README.md',
    'pyproject.toml',
]


def build_conf_files(config_type, backend):
    """Build a list of configuration file (relative) pathnames of the
    configuration files the cookiecutter creates."""
    config_paths = [f'{config_basename}.{config_type}'
                    for config_basename in CONFIG_BASENAMES]
    if config_type != 'ini' and backend == 'sqlalchemy':
        # alembic needs .ini config files
        config_paths.extend([f'alembic_{config_basename}.ini'
                             for config_basename in CONFIG_BASENAMES])
    return config_paths


def build_files_list(root_dir):
    """Build a list containing relative paths to the generated files."""
    file_list = []
    for dirpath, subdirs, files in os.walk(root_dir):
        for file_path in files:
            file_list.append(os.path.join(dirpath[len(root_dir):], file_path))

    return file_list


@pytest.mark.parametrize('config_type', CONFIG_EXTS)
@pytest.mark.parametrize('template', ['jinja2', 'mako', 'chameleon'])
def test_base(cookies, venv, capfd, template, config_type):
    result = cookies.bake(extra_context={
        'project_name': 'Test Project',
        'template_language': template,
        'configuration_file_type': config_type,
        'backend': 'none',
        'repo_name': 'myapp',
    })

    assert result.exit_code == 0

    out, err = capfd.readouterr()

    expected_files = BASE_FILES.copy()
    expected_files.extend(build_conf_files(config_type, 'none'))

    if WIN:
        assert 'Scripts\\pserve' in out
        for idx, base_file in enumerate(expected_files):
            expected_files[idx] = base_file.replace('/', '\\')
    else:
        assert 'bin/pserve' in out

    expected_files.sort()

    # Get the file list generated by cookiecutter. Differs based on backend.
    files = build_files_list(str(result.project_path))
    files.sort()

    # Rename files based on template being used
    if template == 'chameleon':
        template = 'pt'

    for idx, base_file in enumerate(expected_files):
        if 'templates' in base_file:
            expected_files[idx] = expected_files[idx].split('.')[
                0] + '.' + template

    assert expected_files == files

    cwd = str(result.project_path)

    # this is a hook for executing scaffold tests against a specific
    # version of pyramid (or a local checkout on disk)
    if 'OVERRIDE_PYRAMID' in os.environ:  # pragma: no cover
        venv.install(os.environ['OVERRIDE_PYRAMID'], editable=True)

    venv.install(cwd + '[testing]', editable=True)
    subprocess.check_call([venv.python, '-m', 'pytest', '-q'], cwd=cwd)


@pytest.mark.parametrize('config_type', CONFIG_EXTS)
@pytest.mark.parametrize('template', ['jinja2', 'mako', 'chameleon'])
def test_zodb(cookies, venv, capfd, template, config_type):
    result = cookies.bake(extra_context={
        'project_name': 'Test Project',
        'template_language': template,
        'configuration_file_type': config_type,
        'backend': 'zodb',
        'repo_name': 'myapp',
    })

    assert result.exit_code == 0

    out, err = capfd.readouterr()

    expected_files = ZODB_FILES.copy()
    expected_files.extend(build_conf_files(config_type, 'zodb'))

    if WIN:
        assert 'Scripts\\pserve' in out
        for idx, zodb_file in enumerate(expected_files):
            expected_files[idx] = zodb_file.replace('/', '\\')
    else:
        assert 'bin/pserve' in out

    expected_files.sort()

    # Get the file list generated by cookiecutter. Differs based on backend.
    files = build_files_list(str(result.project_path))
    files.sort()

    # Rename files based on template being used
    if template == 'chameleon':
        template = 'pt'

    for idx, zodb_file in enumerate(expected_files):
        if 'templates' in zodb_file:
            expected_files[idx] = expected_files[idx].split('.')[
                0] + '.' + template

    assert expected_files == files

    cwd = str(result.project_path)

    # this is a hook for executing scaffold tests against a specific
    # version of pyramid (or a local checkout on disk)
    if 'OVERRIDE_PYRAMID' in os.environ:  # pragma: no cover
        venv.install(os.environ['OVERRIDE_PYRAMID'], editable=True)

    venv.install(cwd + '[testing]', editable=True)
    subprocess.check_call([venv.python, '-m', 'pytest', '-q'], cwd=cwd)


@pytest.mark.parametrize('config_type', CONFIG_EXTS)
@pytest.mark.parametrize('template', ['jinja2', 'mako', 'chameleon'])
def test_sqlalchemy(cookies, venv, capfd, template, config_type):
    result = cookies.bake(extra_context={
        'project_name': 'Test Project',
        'template_language': template,
        'configuration_file_type': config_type,
        'backend': 'sqlalchemy',
        'repo_name': 'myapp',
    })

    assert result.exit_code == 0

    out, err = capfd.readouterr()

    expected_files = SQLALCHEMY_FILES.copy()
    expected_files.extend(build_conf_files(config_type, 'sqlalchemy'))

    if WIN:
        assert 'Scripts\\pserve' in out
        for idx, sqlalchemy_file in enumerate(expected_files):
            expected_files[idx] = sqlalchemy_file.replace('/', '\\')
    else:
        assert 'bin/pserve' in out

    expected_files.sort()

    # Get the file list generated by cookiecutter. Differs based on backend.
    files = build_files_list(str(result.project_path))
    files.sort()

    # Rename files based on template being used
    if template == 'chameleon':
        template = 'pt'

    for idx, sqlalchemy_file in enumerate(expected_files):
        if 'templates' in sqlalchemy_file:
            expected_files[idx] = expected_files[idx].split('.')[
                0] + '.' + template

    assert expected_files == files

    cwd = str(result.project_path)

    # this is a hook for executing scaffold tests against a specific
    # version of pyramid (or a local checkout on disk)
    if 'OVERRIDE_PYRAMID' in os.environ:  # pragma: no cover
        venv.install(os.environ['OVERRIDE_PYRAMID'], editable=True)

    venv.install(cwd + '[testing]', editable=True)

    if config_type == 'ini':
        alembic_cfg_file = 'testing.ini'
    else:
        alembic_cfg_file = 'alembic_testing.ini'
    create_migration_script = textwrap.dedent(
        f'''
        import alembic.config
        import alembic.command

        config = alembic.config.Config('{alembic_cfg_file}')
        alembic.command.revision(
            config,
            autogenerate=True,
            message='init',
        )
        '''
    )
    subprocess.check_call([venv.python, '-c', create_migration_script], cwd=cwd)
    subprocess.check_call([venv.python, '-m', 'pytest', '-q'], cwd=cwd)


def test_it_invalid_module_name(cookies, venv, capfd):
    result = cookies.bake(extra_context={
        'repo_name': '0invalid',
    })
    assert result.exit_code == -1
